version: 2

jobs:
  build:
    branches:
      only:
        - cairo-main
    docker:
      - image: ubuntu:bionic
    steps:
      - run:
          name: Installing sudo
          command: |
            apt-get update
            apt-get install -y sudo
            rm -rf /var/lib/apt/lists/*

      - run:
          name: Installing Build System
          command: |
            apt-get update
            apt-get install -y git build-essential libboost-system-dev cmake python2.7
            apt-get install -y curl cpio

      - checkout
      - run:
          name: Setup 3rd Party Modules
          command: |
            git submodule sync
            git submodule update --init
            cd third_party
            curl https://home.hiroshima-u.ac.jp/mpsuzuki/skia-m70_ubuntu1804_20190517.cpio.xz | xz -cd | cpio -vidum

      - run:
          name: Creating Build Files
          command: |
            cd svgnative
            cmake -Bbuild/linux -H. -DSTYLE=ON -DUSE_SKIA=ON -DUSE_CAIRO=ON -DUSE_SKIA_EXAMPLE=ON -DUSE_CAIRO_EXAMPLE=ON

      - run:
          name: Creating Binary Files
          command: |
            cd svgnative
            make -C build/linux

      - run:
          name: Run tests
          command: |
            cd svgnative
            /usr/bin/python2.7 script/runTest.py --test=test
